add similarity test
lukaslueg/hyperminhash pull request #2
Opened 2024-05-09 03:19 UTC by jianshu93

Add similarity test, about 10% error for Jaccard at about 0.01, consistent with the paper. Please merge if you find it useful. I would also suggest a comparison with SetSketch, please see the issue I opened.

Thanks,

Jianshu

2024-05-09 08:15 UTC, lukaslueg commented
Thanks for the PR. CI seems legit, please address those

2024-05-09 14:06 UTC, jianshu93 commented
Should be working this time?

Jianshu

2024-05-09 20:34 UTC, lukaslueg commented
Nope :-)

If you run `cargo fmt` // `cargo clippy` locally, you should get the same result as CI. Otherwise, refer to the log

2024-05-09 23:44 UTC, jianshu93 commented
Hello @lukaslueg ,

Cargo clippy did not pass with nightly 1.78:

error: usage of a legacy numeric method
  --> src/lib.rs:68:24
   |
68 | const MAXX: u64 = u64::max_value() >> MAX;
   |                        ^^^^^^^^^^^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#legacy_numeric_constants
   = note: `-D clippy::legacy-numeric-constants` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(clippy::legacy_numeric_constants)]`
help: use the associated constant instead
   |
68 | const MAXX: u64 = u64::MAX >> MAX;
   |                        ~~~

    Checking crossbeam-epoch v0.9.18
    Checking crossbeam-queue v0.3.11
    Checking crossbeam-channel v0.5.12
error: usage of a legacy numeric constant
   --> src/lib.rs:207:13
    |
207 |             std::f64::INFINITY
    |             ^^^^^^^^^^^^^^^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#legacy_numeric_constants
help: use the associated constant instead
    |
207 |             f64::INFINITY
    |

error: could not compile `hyperminhash` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...

I think I cannot do more before you can fix this error. 

Thanks,

Jianshu

2024-05-10 06:37 UTC, lukaslueg requested changes

2024-05-10 06:37 UTC, lukaslueg commented on src/lib.rs
> +        let _union_size = sketch1.clone().union(&sketch2).cardinality();
If `_union_size` is unused, the whole line should be removed.

2024-05-10 06:37 UTC, lukaslueg commented on src/lib.rs
> +
This blank line is causing a `rustfmt` error

2024-05-10 14:41 UTC, jianshu93 commented
Fixed!

2024-05-10 21:09 UTC, lukaslueg commented
The final blank line is still causing a rustfmt error

2024-05-10 21:19 UTC, jianshu93 commented
Sorry for the lack of experience in using clippy and format. I love it after trying so many times (no such tools that can help with formatting to have very high quality code in other languages). I normally just did cargo build and then pass. By the way for the nightly rust v1.80, there are errors there for clippy. It will take some time to have the problem on stable rust, but just to let you know.

Jianshu

2024-05-11 09:50 UTC, merged